### ISSUE TITLE
Change Method Signature should allow users to provide default values for new arguments

### ISSUE THREAD

**Issue by younata** [tjarratt/Xcode-Better-Refactor-Tools#1]
Also, while I'm at it, can I get write access to the tracker?

**Comment by tjarratt** [comment]
Added you as an owner to the Pivotal Tracker backlog.

With great power comes yadda yadda yadda.

**Comment by tjarratt** [comment]
Closing since this is no longer possible. The Xcode plugin has been deprecated (and deleted) in favor of a small CLI.
