### ISSUE TITLE
swift fakes should not use ++ to increment call counts.

### ISSUE THREAD

**Issue by younata** [tjarratt/Xcode-Better-Refactor-Tools#10]
Instead of generating code along the lines of 

```
func beginWork(callback: WorkFlowFinishCallback) {
    self.beginWorkCallCount++
    self.beginWorkArgs.append(callback)
}
```

it should instead use the `+=` operator to increment the call count, as `++` will be removed in swift 3

See [Swift Evolution Proposal #4](https://github.com/apple/swift-evolution/blob/master/proposals/0004-remove-pre-post-inc-decrement.md).

**Comment by tjarratt** [comment]
Fixed by #11. Thanks @younata and @joemasilotti!
