### ISSUE TITLE
Strip whitespace on types during code generation

### ISSUE THREAD

**Issue by tjarratt** [tjarratt/Xcode-Better-Refactor-Tools#17]
We should generate higher quality source code with fewer formatting oddities.

For example, if you have some code that looks like this:

MyFunkyStuff.swift
```swift
protocol MyFunkyStuff
    func isFunky(name: String) -> Bool
}
```

It appears that fake4swift will sometimes include whitespace characters around the return type of the methods it generates. 

FakeMyFunkyStuff.swift
```swift
class FakeMyFunkyStuff

// snip
    func isFunky(name: String) -> (Bool
) { // woah what is going on here
        self.isFunkyCallCount += 1
        self.isFunkyArgs.append((name))
        return self.isFunkyStub!(name)
    }
// snip
```

**Comment by younata** [comment]
This happens mostly when your protocol uses generics.

E.G. your protocol looks like:

```swift
protocol MyProtocolWithGeneric {
    func foo() -> Bar<Baz>
}
```

**Comment by younata** [comment]
Actually caused by unicode!
